name: 'Build Idris2'
on:
  push:
    branches: ['main']
  schedule:
    - cron: "0 0 * * 0"
jobs:
  buildIdris2:
    name: Build Idris2
    runs-on: ubuntu-latest
    steps:
      - name: Get latest idris2 release
        id: idris2release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: idris-lang/Idris2
          excludes: prerelease, draft
      - name: Get latest build
        id: idris2build
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: sergeyshpadyrev/setup-idris-builds
          excludes: prerelease, draft
      - name: Checkout idris2 repository
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          path: idris2-source
          ref: ${{ steps.idris2release.outputs.release }}
          repository: idris-lang/Idris2
      - name: Install dependencies
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        run: sudo apt-get -y install build-essential clang chezscheme
      - name: Build idris2
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        run: |
          cd idris2-source
          export SCHEME=scheme
          export PATH="${PATH}:~/.idris2/bin"
          make bootstrap
          make install
      - name: Archive build
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        run: tar -zcvf idris2-ubuntu.tar.gz -C $HOME .idris2
      - name: Upload archive to release
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: idris2-ubuntu.tar.gz
          body: "Latest Idris2 build"
          file: idris2-ubuntu.tar.gz
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.idris2release.outputs.release }}
      - name: Set up Docker Buildx
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: docker/login-action@v2
        with:
          username: sergeyshpadyrev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: actions/checkout@v3
      - name: Build and push
        if: steps.idris2release.outputs.release != steps.idris2build.outputs.release
        uses: docker/build-push-action@v3
        with:
          build-args: |
            idris_build_version=${{ steps.idris2release.outputs.release }}
          context: .
          push: true
          tags: sergeyshpadyrev/idris:latest
        
