name: 'Build Idris2'
on:
  push:
    branches: ['main']
  schedule:
    - cron: "0 0 * * 0"
jobs:
  buildIdris2:
    name: Deploy staging
    runs-on: ubuntu-latest
    steps:
      - name: Get latest idris2 release
        id: idris2release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: idris-lang/Idris2
          excludes: prerelease, draft
      - name: Checkout idris2 repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          path: idris2-source
          ref: ${{ steps.idris2release.outputs.release }}
          repository: idris-lang/Idris2
      - name: Install dependencies
        run: sudo apt-get -y install build-essential clang chezscheme
      - name: Checkout to latest tag
      - name: Build idris2
        run: |
          cd idris2-source
          export SCHEME=scheme
          export PATH="${PATH}:~/.idris2/bin"
          make bootstrap
          make install
      - name: Archive build 
        run: tar -zcvf idris2-ubuntu.tar.gz -C $HOME .idris2
      - name: Upload archive to release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: idris2-ubuntu.tar.gz
          body: "Latest Idris2 build"
          file: idris2-ubuntu.tar.gz
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
        
