name: 'Test action'
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ['main']
jobs:
  testIdrisAction:
    name: Test setup-idris action 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Idris
        uses: sergeyshpadyrev/setup-idris@v1
      - name: Check setup
        run: |
          idris -v
          idris2 -v
      - name: Compile program
        run: idris main.idr -o main
      - name: Run compiled program
        run: ./build/exec/main
      
